### PR TITLE
Fix #241: Handle negative offsets, leap year support, preserve DayOfWeek for ByWeekNo

### LINKED ISSUE #241: Recur.getNextDate() does not handle negative offsets well or at all
**Describe the bug**

`Recur.getNextDate()` is throwing an `ArrayIndexOutOfBoundsException` for some (legal) negative offsets for BYYEARDAY, BYMONTHDAY & BYWEEKNO.

**To Reproduce**
1. Create an RRULE.
2. Add a ByYearDay with -366, ByMonthDay with -31 during a month that has less than 31 days. Or seemingly any negative offset in a ByWeekNo rule.
3. Call `getNextDate()`.
4. Will throw `ArrayIndexOutOfBoundsException`.

**Expected behavior**
A negative offset in an RRULE is supposed to count back from the last week/day of the period. For example, BYMONTHDAY=-1,-2,-3 means on the last, second-last and third-last days of the month. So just as BYMONTHDAY=31 is the last day of the month if the month has 31 days and is skipped otherwise, so too BYMONTHDAY=-31 should be the first day of the month if the month has 31 days and is skipped otherwise.

Similar comments apply to BYYEARDAY of -366 - should be on the first day of the year if it's a leap year, or skipped if it's not a leap year.

It also seems that *any* negative offset causes AIOOBException with a ByWeekNo. It should count back from the last week of the year. Adding to the confusion, the spec is not 100% explicit about the definition of the "last week of the year", but I think we can safely infer from the definition of the first week as to which year that border week is reckoned to belong to, and use that for the definition of "last week".

**Environment (please complete the following information):**
 - Windows 10
 - Java Version 9.0.4
- ical4j version 2.0.2

**Additional context**
* It is possible that other areas of recurrence set generation in Recur may be affected. I have not tested them as my immediate need is for getNextDate() to work.
* It is also possible that negative offsets in ByDay rules may be affected. I have not tested these either.
* This could possibly be related to #39.
* Admittedly these are not common use cases. But because they are not common they are also more likely to cause tricky and inconvenient bugs in downstream code if they don't work.

PS: Thanks for the library!

### PR DESCRIPTION
**Pull request by kriegfrj**
This PR contains a number of fixes for the issues raised in #241 and also for a number of other esoteric cases:

* The biggest fix is for negative offsets. These now work properly. Hopefully they are calculated more efficiently too.
* Also found that leap years weren't being handled properly - if you specify a ByYearDay of 366 and the given year wasn't a leap year, then it would add the first of January from the *next* year instead. Eg: `FREQ=YEARLY;BYYEARDAY=2,365,366' with a start date of 2016-01-01 would generate: `2016-01-02, 2016-12-30, 2016-12-31, 2017-01-02, 2017-12-31, *2018-01-01*, 2018-02-01...`. This has now been fixed so that day 366 is dropped 
* Prior to this fix, the behaviour when ByWeekNo was used without a ByDay was a little counterintuitive - and, I believe, not in accordance with RFC 5545 (though admittedly the spec isn't crystal clear on this). I think that the relevant part of RFC 5545 is this:

````
Information, not contained in the rule, necessary to determine the
      various recurrence instance start time and dates are derived from
      the Start Time ("DTSTART") component attribute.  For example,
      "FREQ=YEARLY;BYMONTH=1" doesn't specify a specific day within the
      month or a time.  This information would be the same as what is
      specified for "DTSTART".
````

Now, there are three ways to specify a day in a calendar:
1. Year + DayOfYear
2. Year + Month + DayOfMonth (common, everyday date format)
3. Year + WeekNo + DayOfWeek.

As the RFC example states, if the day of month is not specified for a ByMonth rule, then it should come from DTSTART - then so too if the day of week is not specified for a ByWeekNo rule then it should come from DTSTART.

The existing implementation, however, preserves the day-of-month rather than the day-of-week even when using a ByWeekNo rule. So the following rule:
`FREQ=YEARLY;BYWEEKNO=2;WKST=MO;DTSTART=20180102`
...generates the following sequence:
`Tuesday 2018-01-09, Wednesday 2019-01-09, Thursday 2020-01-09...`
...which is probably not what was intended (and if it was intended, then it could have been generated with `FREQ=YEARLY;BYYEARDAY=9`). After this patch, the result will be:
`Tuesday 2018-01-09, Tuesday 2019-01-08, Wednesday 2020-01-07...`
...ie, preserving the DayOfWeek setting from DTSTART.

One edge case that I'm not sure how to handle (and the spec is even less clear than for the above) is when the first/last week of the year actually spans the year boundary. Should days that are outside the base year be excluded, or included? For example:
`FREQ=YEARLY;BYWEEKNO=1;WKST=MO;DTSTART=20180102`
Is the correct result:
`Tuesday 2018-01-02, Tuesday 2019-01-01, Tuesday 2019-12-31 (this is actually week 1 of 2020), Tuesday 2021-01-05...`
...or is it:
`Tuesday 2018-01-02, Tuesday 2019-01-01, Tuesday 2021-01-05...`
...skipping the instance where Tuesday of the first week didn't actually fall within the same year.

At the moment, the implementation in this PR includes Tuesday 2019-12-31. I'd be interested in having anyone's feedback on this; I'm thinking that maybe it should be like the leap year (ie, simply drop it if week 1 doesn't have that particular day-of-week in that particular year).

### CODE REVIEW

**Comment by kriegfrj** [comment]
> After this patch, the result will be:
> `Tuesday 2018-01-09, Tuesday 2019-01-08, Wednesday 2020-01-07...`

Sorry, that was a typo - the above should have read:
`Tuesday 2018-01-09, Tuesday 2019-01-08, Tuesday 2020-01-07...`

Apologies for any confusion.

I also note that in the code coverage report, coverage of Dates went down. That is because in this patch `Recur` no longer uses `Dates.getAbsYearDay()`, `Dates.getAbsMonthDay()` or `Dates.getAbsWeekNo()`. Indeed, as far as I can tell these functions are no longer used anywhere in the library, and they are still buggy in that they don't handle negative offsets properly. I would have deleted them, were it not for the fact that they were public methods in a public class.

**Comment by benfortuna** [comment]
Ok thanks. I may remove the getAbs*() methods anyway as the next release is a major version (3.0.0)

**Comment by benfortuna** [comment]
Also, as to the final question about inclusion of week for those spanning year boundaries, I guess I'd have two points.

1. This was probably avoided when using the day-of-month, however I think your argument for using day-of-week does make a lot of sense

2. Rather than drop the occurrence (or include occurrences beyond the year boundary) I wonder if it makes sense to roll the date forward to the first day of the week within the year boundary (Wednesday in your example)? Or does that not comply with the logic of the rule?

**Comment by benfortuna** [comment]
On the topic of the specification ambiguities, this PR has been a bit of a catalyst for a broader discussion about recurrence rule inheritance at calconnect.

Calconnect (http://calconnect.org) is a consortium of calendar software vendors and enthusiasts that work together on issues of calendar interoperability.

For issues like this, where the specifications are open to interpretation, calconnect can often provide guidance on how other vendors implement their solution.

So just waiting to see if there is a general consensus on this issue, but at this stage I think it's likely to be similar to your approach.

**Comment by kriegfrj** [comment]
Thanks for the update, Ben. Is that discussion on Calconnect publically available? If not, then can you keep us updated? If so, then (if it's not too difficult) can you please post a link to it here?

Also, since my last update, I've been thinking about how this works with regard to month rules. At the moment, if (eg) the seed date is on the 31st of Jan, and you have a monthly rule, the ical generator will go 31st Jan, 28th Feb, 28th March, 28th of April, etc rather than 31st Jan, 31st Mar, 31st May, etc (ie, smart-adjust the day-of-month to maintain the "monthly" frequency, rather than be strict on the day-of-month and drop dates) . Again, there is no specific reference to this in the documentation, but this does kinda make sense - if you wanted to be strict about the day-of-month, you probably would have (even should have) specified the day of month. If you want to always be on the last day of the month, you can use the ByMonthDay=-1 for that. So I think that rolling forward/back makes sense in that case.

That being the case, this is an argument in favor for "rolling forward/backward" if the day-of-week is not explicitly specified in a ByDay rule. If the user definitely wants (eg) a Wednesday, they can specify a Wednesday explicitly. So I think there are three different possibilities that have some internal consistency:

1. Include a day-of-week even if it falls outside of the year boundary, and always use the day-of-week from the seed date.
2. Only include a day-of-week if it falls within the year boundary. If it falls outside the year boundary:
2.a. if day-of-week has been implied by the seed date, then roll back/forward to within the year boundary;
2.b. otherwise if day-of-week has been specified explicitly, omit that recurrence.
3. Only include a day-of-week if it falls within the year boundary. Always omit otherwise, even in the implicit case. 

Then there is also a question on what to do in the next year if the day-of-week is rolled - do you use the rolled day-of-week for the next year (which may roll again)? Or do you revert to the seed day-of-week?

Or perhaps these exceptions are just too complicated, and the spec should simply make ByDay a mandatory field if ByWeekNo is present?

**Comment by benfortuna** [comment]
Copied from calconnect mailing list:

Implicit selection rules of RFC 5545


In RFC 5545 the evaluation of certain repeat rules also relies on implicit selection rules inherited indirectly from the initial start date.


Specifically,
— when the ‘FREQ’ parameter is set to ‘WEEKLY’, but without a ‘BYDAY’ parameter, the ‘BYDAY’ selection is inherited from the calendar day of week value from the initial start date;
— when the ‘FREQ’ parameter is set to ‘MONTHLY, but without a ‘BYMONTHDAY’ parameter, the ‘BYMONTHDAY’ selection is inherited from the calendar month of year value from the initial start date;


— when the ‘FREQ’ parameter is set to ‘YEARLY’ but without a ‘BYYEARDAY’ parameter,
—  if no ‘BYMONTH’ or ‘BYWEEKNO’ parameter is set:
— if the ‘BYMONTHDAY’ parameter is provided, then the ‘BYMONTH’ selection is inherited from the calendar month of year value from the initial start date;
— if the ‘BYDAY’ parameter is not set, then the ‘BYMONTH’ selection is inherited from the calendar month of year value from the initial start date;
—  if no ‘BYMONTHDAY’, ‘BYWEEKNO’ or ‘BYDAY’ parameter is set, the ‘BYMONTHDAY’ selection is inherited from calendar day of month of the initial start date;
—  if there is a ‘BYWEEKNO’ parameter set but no ‘BYMONTHDAY’ or ‘BYDAY’, the ‘BYDAY’ selection is inherited from the calendar day of week of the initial start date.

EXAMPLE  In evaluating a simplified example expression from RFC 5545, with ‘DTSTART’ set to ‘19970902T090000’ and ‘RRULE’ set to ‘FREQ=WEEKLY;INTERVAL=2’, will result in the instance series of “1997 September 2, 16, 30; October 14…”. This resulting instance series relies on an implicit understanding that ‘FREQ=WEEKLY’ always requires selection of the ‘BYDAY’ parameter, which is not specified in the original selection rule. In this case, ‘BYDAY’ is implicitly set to Tuesdays as originally obtained from the ‘DTSTART’ value being a Tuesday.

**Comment by benfortuna** [comment]
I think the text in previous comment from calconnect mailing list doesn't address the boundary scenario above, but does seem consistent with this PR on value inheritance from DTSTART.

Will merge this and we can refine later if need be. Many thanks for the contribution, and apologies for delay in applying it.

**Pull request merged**
