### PR TITLE
update to java 8

### PR DESCRIPTION
**Pull request by codylerum**
For #104

Having the threeten backport or joda at this point creates a lot of overlapping import suggestions for those on java 8 and up.

I propose doing a 3.0 which targets jdk8. This gets to the new Date/Time library and should be the last bump needed for a while.

Anyone starting a new project should really be at 8 or higher at this point and v2 will still be around for those that need it.

### CODE REVIEW

**Comment by benfortuna** [comment]
Hi Cody, it's a fair point. I would have liked to make some more progress on porting to the new date/time API, but it's going to require quite some effort I think.

As much as we'd like everyone to use Java 8 I know in the enterprise a lot of organisations get stuck on earlier Java versions, so I'd like to look at creating a Java 7 backport branch before fully committing to minimum Java 8. Will look into this in the next week or so.

**Comment by codylerum** [comment]
@benfortuna Thanks Ben. Obviously it's something we can work around, but would be good to start moving things that direction. Especially since Java 8 is a real break point in Java's Date/Time story.

As you can see my PR is trivial so feel free to close it and just roll it on your own when you are ready.

**Comment by benfortuna** [comment]
I've added pr #233 that includes your changes and some more code clean up. This will mark the start of the 3.x release series

**Comment by codylerum** [comment]
👍

**Pull request closed without merging**
