### PR TITLE
Issue #154 Alternate fix of thread unsafe use of ServiceLoader

### PR DESCRIPTION
**Pull request by peterdivvito**
This pull request is an alternative to pull request #155.

I realised that the use of ParameterFactoryImpl.getIntance() and ProtertyFactoryImpl.getInstance() was unnecessary as the properties and parameters already know how to build themselves.

This is again a breaking change for anyone creating their own property/parameter types.

I am interested to hear your thoughts on the best approach.

Peter

### CODE REVIEW

**Comment by benfortuna** [comment]
Hi peter, thanks for the contributions. I'll definitely take a look at the two approaches to see what the differences are. 

A third alternative I am considering is to remove ServiceLoader completely. It doesn't appear to play well with Android or OSGi, so I'm thinking an alternative dependency injection approach may be better. Dagger looks interesting, basically a subset of guice that works with Android. If this is a suitable alternative we may be able to remove ServiceLoader and even some of the factories.

http://square.github.io/dagger/

**Comment by benfortuna** [comment]
@peterdivvito I think this is actually a good way to go and cleans up the code quite a bit. I'll do a full review but most likely will use this approach. Many thanks for the hard work.

**Comment by peterdivvito** [comment]
My pleasure.

**Comment by peterdivvito** [comment]
Hi @benfortuna, any idea on when this fix will be published to maven?

At the moment I'm using git submodules to make sure the fixes are a part of my deployment but they are a pain in the @#$%.

**Comment by benfortuna** [comment]
Hopefully in the next couple of weeks. Due to the changes in the API (i.e. removal of factory singleton) I'm going to bump the minor version to 2.1.0. I'm just trying to get some other changes processed to push out a final 2.0.x release first.

**Comment by peterdivvito** [comment]
Hi @benfortuna, any eta on getting this released?

**Pull request merged**
