### PR TITLE
Support escaped \; in GEO fields

### PR DESCRIPTION
**Pull request by ljrk0**
SOGo by Inverse Inc. escapes semicolons in the Geo fields leading to
errors such as:

    Caused by: net.fortuna.ical4j.data.ParserException: Error at line 9:null
    	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:17)
    	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:3)
    	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:2)
    	at at.bitfire.ical4android.ICalendar$Companion.fromReader(ICalendar.kt:4)
    	... 37 more
    Caused by: java.lang.NumberFormatException
    	at java.math.BigDecimal.<init>(BigDecimal.java:497)
    	at java.math.BigDecimal.<init>(BigDecimal.java:383)
    	at java.math.BigDecimal.<init>(BigDecimal.java:809)
    	at net.fortuna.ical4j.model.property.Geo.setValue(Geo.java:3)
    	at net.fortuna.ical4j.model.property.Geo.<init>(Geo.java:7)
    	at net.fortuna.ical4j.model.property.Geo$Factory.createProperty(Geo.java:1)
    	at net.fortuna.ical4j.model.PropertyBuilder.build(PropertyBuilder.java:5)
    	at net.fortuna.ical4j.data.DefaultContentHandler.endProperty(DefaultContentHandler.java:3)
    	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:15)
    	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(Unknown Source:0)
    	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:7)
    	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:7)
    	at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(Unknown Source:0)
    	at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:5)
    	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendar(CalendarParserImpl.java:6)
    	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:2)
    	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:13)
    	... 40 more

    LOCAL RESOURCE
    null

    REMOTE RESOURCE
    https://redacted.com/url/to/calendar_file_with_geo.ics

This patch introduces a new Compatibility Hint in order to successfully
parse such files as well as adding test cases for the Groovy spec as
well as the line accuracy test in the parser itself.

### CODE REVIEW

**Comment by ljrk0** [comment]
I'm not really fluent with either Java, Groovy nor the naming conventions, so feedback is appreciated :-)

Currently the compatibility option simply switches the behavior from conformant to sogo-nonspec.  It mostly served as a playground for me to find what files I need to edit.

Generally I tried to keep the public methods backwards compatible though, by providing one with a default value with compatibility set to false in order to keep existing behavior.

**Comment by ljrk0** [comment]
I've implemented my idea on how to implement the fallback logic, but I'm open to suggestions on how to do this properly.

**Comment by benfortuna** [comment]
@ljrk0 Thanks for the contribution, very much appreciated. 

You'll notice I've implemented the change slightly different by using regex parsing instead of substring, as I think it is a simpler approach when trying to manage multiple parsing formats.

I also would prefer to just use the existing RELAXED_PARSING CompatibilityHint to activate the relaxed format, as it also keeps the configuration simple, but let me know if you can think of a use-case where a separate hint would be required.

**Comment by ljrk0** [comment]
Hi Ben, thanks for the feedback!  I think both changes sound more than reasonable, the code looks more clean this way.

I'm happy for the change to land, thanks for maintaining this library.

On 6 August 2022 23:59:16 UTC, Ben Fortuna ***@***.***> wrote:
***@***.*** Thanks for the contribution, very much appreciated. 
>
>You'll notice I've implemented the change slightly different by using regex parsing instead of substring, as I think it is a simpler approach when trying to manage multiple parsing formats.
>
>I also would prefer to just use the existing RELAXED_PARSING CompatibilityHint to activate the relaxed format, as it also keeps the configuration simple, but let me know if you can think of a use-case where a separate hint would be required.
>
>

**Comment by benfortuna** [comment]
Closing PR with partial merge of changes already complete. Thx again for the contribution.

**Comment by rfc2822** [comment]
Thanks… would it be possible to backport this to the 3.x version, too? It would surely reduce problems caused by these invalid GEO strings (we often see them).

**Comment by benfortuna** [comment]
@rfc2822 yup it was backported to 3.x and should be available from release 3.2.5. Let me know if you are still seeing some issues (note the RELAXED_PARSING hint needs to be enabled).

**Comment by rfc2822** [comment]
> @rfc2822 yup it was backported to 3.x and should be available from release 3.2.5. Let me know if you are still seeing some issues (note the RELAXED_PARSING hint needs to be enabled).

Ah, sorry, my fault. The last problematic GEO properties we have encountered were:

```
GEO:
GEO:0
GEO:48.786829
```

They all stop the processing of the whole iCalendar instead of just ignoring the GEO field, like users would expect. But that is more related to #454 and probably not topic of this PR.

**Pull request closed without merging**
