### PR TITLE
Feature/optional jcache

### PR DESCRIPTION
**Pull request by benfortuna**

### CODE REVIEW

**Comment by rfc2822** [comment]
Thank you!

Without an `ical.properties` (I have configured it within a static code block), I get a `NullPointerException` because `CONFIG` seems to be null:

```
java.lang.ExceptionInInitializerError
    at net.fortuna.ical4j.util.Configurator.getProperty(Configurator.java:75)
    at net.fortuna.ical4j.util.CompatibilityHints.<clinit>(CompatibilityHints.java:87)
    at net.fortuna.ical4j.util.CompatibilityHints.setHintEnabled(CompatibilityHints.java:107)
    at at.bitfire.ical4android.iCalendar.<clinit>(iCalendar.kt:36)
    at at.bitfire.davdroid.resource.LocalEvent.<clinit>(LocalEvent.kt:26)
...
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.Reader.read(char[])' on a null object reference
    at java.util.Properties$LineReader.readLine(Properties.java:435)
    at java.util.Properties.load0(Properties.java:354)
    at java.util.Properties.load(Properties.java:342)
    at net.fortuna.ical4j.util.Configurator.<clinit>(Configurator.java:58)
    at net.fortuna.ical4j.util.Configurator.getProperty(Configurator.java:75) 
    at net.fortuna.ical4j.util.CompatibilityHints.<clinit>(CompatibilityHints.java:87) 
    at net.fortuna.ical4j.util.CompatibilityHints.setHintEnabled(CompatibilityHints.java:107) 
    at at.bitfire.ical4android.iCalendar.<clinit>(iCalendar.kt:36) 
    at at.bitfire.davdroid.resource.LocalEvent.<clinit>(LocalEvent.kt:26) 
...
```

I'll try to use ical.properties instead of static configuration.

**Comment by rfc2822** [comment]
Another problem is that `Optional.orElse()` is called with an object argument instead of a lambda function:

```
return property.orElse(new JCacheTimeZoneCache());
```

This causes `new JCacheTimeZoneCache()` to be evaluated even when `property` is already set (to the Map config cache, for instance). This constructor call looks for a JCache implementation, which of course fails:

``` 
Caused by: javax.cache.CacheException: No CachingProviders have been configured
at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:381)
at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:351)
at javax.cache.Caching.getCachingProvider(Caching.java:142)
at net.fortuna.ical4j.util.JCacheTimeZoneCache.<init>(JCacheTimeZoneCache.java:15)
```

Then it throws a `CacheException`, which is not catched.

So I suggest to use `Optional.orElseGet()` [https://docs.oracle.com/javase/8/docs/api/index.html?java/util/Optional.html] instead. Using the `Supplier` as lambda pattern will avoid calling the `new JCacheTimeZoneCache()` constructor.

**Comment by benfortuna** [comment]
Ok, thanks for pointing out the bug. I've put in a fix now as you suggested - I actually implemented my own `Optional` class to avoid a dependency on java 8, but wasn't hard to add `Supplier` also.

I think I fixed the null pointer issue also when `ical4j.properties` doesn't exist. Let me know if you see further issues.

**Comment by omarkilani** [comment]
Hi Ben,

We updated from 2.1.1 to 2.1.3 and started seeing this:

```
Exception in thread "pool-5-thread-16" java.lang.NoClassDefFoundError: javax/cache/configuration/Configuration
        at net.fortuna.ical4j.model.TimeZoneLoader$2.get(TimeZoneLoader.java:283)
        at net.fortuna.ical4j.model.TimeZoneLoader$2.get(TimeZoneLoader.java:280)
        at net.fortuna.ical4j.util.Optional.orElseGet(Optional.java:31)
        at net.fortuna.ical4j.model.TimeZoneLoader.cacheInit(TimeZoneLoader.java:280)
        at net.fortuna.ical4j.model.TimeZoneLoader.<init>(TimeZoneLoader.java:80)
        at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:125)
```

Is there some way to opt out of this jcache dependency?

**Comment by benfortuna** [comment]
Hi Omar,

Yes you can opt out of the jcache dependency by adding the following entry to your configuration (i.e. `ical4j.properties`):

`net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache`

This will override the default caching implementation to use a simple `HashMap` instead of the more sophisticated Jcache implementation.

The alternative is to just add a Jcache implementation (such as ehcache) to your dependencies.

**Comment by stellingsimon** [comment]
For those trying to configure the cache implementation: Note that `ical4j-2.1.1` uses JCache regardless of what is configured in `net.fortuna.ical4j.timezone.cache.impl`. I didn't test `ical4j-2.1.2`.

**Comment by omarkilani** [comment]
@benfortuna is there any chance you could be convinced to default to MapTimeZoneCache if there's no ical4j.properties found? :)

**Pull request merged**
